In [2]:
import numpy as np

In [3]:
import array

In [22]:
a=np.array([1,2,3,4])

In [23]:
a.ndim

1

In [24]:
a=np.array([[1,2,3,4]])

In [25]:
a.ndim

2

In [28]:
a=np.array([[[1,2,3,4]]])

In [29]:
a.ndim

3

In [30]:
np.array([1,2,3,4,"shi"])
#1.In numpy the array is not homogenous
#2.And it will upcast itself or typecast


array(['1', '2', '3', '4', 'shi'], dtype='<U11')

In [39]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [45]:
np.array([[1,3],[3,4],[6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [49]:
np.array([[1,3],[3,4],[6,7,9]])

C:\Users\hp\AppData\Local\Temp/ipykernel_13156/4008039817.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,4],[6,7,9]])


array([list([1, 3]), list([3, 4]), list([6, 7, 9])], dtype=object)

In [50]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [51]:
np.array([1,2,3] , ndmin = 3)

array([[[1, 2, 3]]])

In [52]:
np.array([1,2,3] , dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [53]:
arr = np.array([(1,2) , (4,5)],dtype = [("a",'<i4'), ("b",'<i8')])

In [54]:
type(arr[0][0])

numpy.int32

In [55]:
type(arr[0][1])

numpy.int64

In [56]:
arr  = np.array([[1,3],[3,4]])

In [57]:
arr

array([[1, 3],
       [3, 4]])

In [58]:
type(arr[0][1])

numpy.int32

In [59]:
mat = np.matrix(arr)

In [60]:
l = [3,4,5,76,7]

In [61]:
np.array(l)

array([ 3,  4,  5, 76,  7])

In [62]:
np.asarray(l)

array([ 3,  4,  5, 76,  7])

In [63]:
np.asanyarray(l)

array([ 3,  4,  5, 76,  7])

In [64]:
np.asanyarray(mat)
#it will convert into array if its already in the form of any array

matrix([[1, 3],
        [3, 4]])

In [65]:
issubclass(np.ndarray,np.matrix )

False

In [77]:
arr

array([[1, 3],
       [3, 4]])

In [67]:
a= arr

In [68]:
b = np.copy(arr)

In [69]:
arr

array([[1, 3],
       [3, 4]])

In [76]:
a

array([[1, 3],
       [3, 4]])

In [72]:
b

array([[1, 3],
       [3, 4]])

In [73]:
arr[-1]

array([3, 4])

In [78]:
type(np.fromfunction(lambda i , j :i==j,(4,4)))

numpy.ndarray

In [79]:
np.fromfunction(lambda i , j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [80]:
np.fromfunction(lambda i , j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [81]:
gen = (i*i for i in range(5))

In [83]:
np.fromiter(range(5),dtype= int)

array([0, 1, 2, 3, 4])

In [84]:
np.fromstring('1,3,4,5,5' , sep = ',', dtype= int)

array([1, 3, 4, 5, 5])

In [85]:
np.fromstring("456 456 3454 34543" ,sep = ' ', dtype= complex)

array([  456.+0.j,   456.+0.j,  3454.+0.j, 34543.+0.j])

In [86]:
arr1 = np.array([[1,2,3,4] , [2,3,4,5] , [4,5,6,7]])

In [87]:
type(arr)

numpy.ndarray

In [88]:
arr1.ndim

2

In [89]:
arr1.size

12

In [90]:
arr1.shape

(3, 4)

In [91]:
arr1.dtype

dtype('int32')

In [92]:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])

In [93]:
arr4.shape

(1, 4, 2, 4)

In [95]:
list(range(6.6,9,.3))

TypeError: 'float' object cannot be interpreted as an integer

In [96]:
np.arange(9,6.6,-.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [97]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [114]:
np.linspace(1,10,5,dtype=int)
#Here 5 is not a jump it is portion and silicing will be accordingly

array([ 1,  3,  5,  7, 10])

In [99]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [100]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [101]:
np.ones(4)

array([1., 1., 1., 1.])

In [102]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [103]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [104]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [105]:
np.linspace([1,6],4,endpoint=False,axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [115]:
np.logspace([2],[3] , axis = 0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [117]:
d = np.linspace(4,7,40)

In [118]:
d.shape

(40,)

In [119]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [120]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [121]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [123]:
np.random.rand(3)

array([0.67551835, 0.14066676, 0.15878635])

In [125]:
np.random.randn(9)#Normal distribution values

array([ 0.39434825,  0.26615892,  2.57938306, -0.05339208,  0.73086562,
        0.75928072, -2.89274687, -1.62354078,  1.10228073])

In [126]:
np.random.randn(2,2,3)

array([[[ 0.05211801, -0.55447925,  0.29973922],
        [ 2.59307285, -0.93995721,  0.28257713]],

       [[-0.08827988, -0.97373572, -0.10367015],
        [ 0.19012217, -0.20078576,  0.82154838]]])

In [127]:
np.random.randint(5,60, (4,4))

array([[59, 20, 38, 14],
       [53, 43, 13, 44],
       [43, 29, 45, 42],
       [43, 31, 45, 18]])

In [128]:
np.random.randn(2,2,3)

array([[[-1.65931578, -0.94730742, -1.08354482],
        [-0.02954994, -1.02103808, -1.31765912]],

       [[-0.75161564,  1.75951772, -0.90354864],
        [ 0.09829245,  0.11301699, -1.52797493]]])

In [130]:
arr = np.random.randint(3,9, ( 3,3))

In [131]:
arr

array([[6, 3, 3],
       [4, 7, 6],
       [7, 5, 5]])

In [132]:
arr.reshape(1,9)

array([[6, 3, 3, 4, 7, 6, 7, 5, 5]])

In [133]:
arr.reshape(9,1)

array([[6],
       [3],
       [3],
       [4],
       [7],
       [6],
       [7],
       [5],
       [5]])

In [134]:
arr.reshape(1,1,9)

array([[[6, 3, 3, 4, 7, 6, 7, 5, 5]]])

In [135]:
arr.reshape(1,1,9)

array([[[6, 3, 3, 4, 7, 6, 7, 5, 5]]])

In [136]:
arr.reshape(3,-198979)

array([[6, 3, 3],
       [4, 7, 6],
       [7, 5, 5]])

In [137]:
arr.reshape(3,-198979)

array([[6, 3, 3],
       [4, 7, 6],
       [7, 5, 5]])

In [138]:
arr.min()

3

In [139]:
arr = np.random.randint(4,100, (5,5))

In [141]:
arr

array([[54, 99, 35, 81, 21],
       [86, 64, 26, 18, 50],
       [51, 69, 77, 69, 59],
       [99, 32, 99, 81, 19],
       [55, 39, 49,  6, 61]])

In [142]:
arr[3: , 3:]

array([[81, 19],
       [ 6, 61]])

In [143]:
arr[:,[1,3]]

array([[99, 81],
       [64, 18],
       [69, 69],
       [32, 81],
       [39,  6]])

In [144]:
arr[arr>10]

array([54, 99, 35, 81, 21, 86, 64, 26, 18, 50, 51, 69, 77, 69, 59, 99, 32,
       99, 81, 19, 55, 39, 49, 61])

In [145]:
arr * arr

array([[2916, 9801, 1225, 6561,  441],
       [7396, 4096,  676,  324, 2500],
       [2601, 4761, 5929, 4761, 3481],
       [9801, 1024, 9801, 6561,  361],
       [3025, 1521, 2401,   36, 3721]])

In [146]:
arr1 = np.random.randint(2,4,(3,3))

In [147]:
arr2 = np.random.randint(2,4,(3,3))


In [148]:
arr1

array([[2, 2, 3],
       [2, 2, 3],
       [3, 2, 3]])

In [149]:
arr2

array([[2, 3, 3],
       [3, 2, 3],
       [3, 2, 3]])

In [150]:
arr1*arr2

array([[4, 6, 9],
       [6, 4, 9],
       [9, 4, 9]])

In [151]:
arr1@arr2
#Matrix mul

array([[19, 16, 21],
       [19, 16, 21],
       [21, 19, 24]])

In [155]:
np.random.seed(30)
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])